from typing import Any, Mapping, Optional, Union

class Code(str):
    def __new__(cls: Any, code: Union[Code, str], scope: Optional[Mapping[str, Any]] = ..., **kwargs: Any) -> Code: ...
    @property
    def scope(self) -> Optional[Mapping[str, Any]]: ...
    def __eq__(self, other: Any) -> Any: ...
    __hash__: Any = ...
    def __ne__(self, other: Any) -> Any: ...
