from collections import abc
from typing import Any, Optional

from bson.codec_options import CodecOptions

class RawBSONDocument(abc.Mapping):
    def __init__(self, bson_bytes: bytes, codec_options: Optional[CodecOptions] = ...) -> None: ...
    @property
    def raw(self) -> bytes: ...
    def items(self): ...
    def __getitem__(self, item: Any): ...
    def __iter__(self) -> Any: ...
    def __len__(self): ...
    def __eq__(self, other: Any) -> Any: ...

DEFAULT_RAW_BSON_OPTIONS: Any
