from collections import abc
from typing import Any, Iterator, Optional

from bson.codec_options import CodecOptions

class RawBSONDocument(abc.Mapping[str, Any]):
    def __init__(self, bson_bytes: bytes, codec_options: Optional[CodecOptions] = ...) -> None: ...
    @property
    def raw(self) -> bytes: ...
    def __getitem__(self, item: str) -> Any: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: Any) -> bool: ...

DEFAULT_RAW_BSON_OPTIONS: CodecOptions
