import datetime
from typing import Any, Union

UPPERBOUND: int

class Timestamp:
    def __init__(self, time: Union[datetime.datetime, int], inc: int) -> None: ...
    @property
    def time(self) -> int: ...
    @property
    def inc(self) -> int: ...
    def __eq__(self, other: Any) -> Any: ...
    def __hash__(self) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    def __lt__(self, other: Any) -> Any: ...
    def __le__(self, other: Any) -> Any: ...
    def __gt__(self, other: Any) -> Any: ...
    def __ge__(self, other: Any) -> Any: ...
    def as_datetime(self) -> datetime.datetime: ...
