from datetime import datetime, timedelta, tzinfo
from typing import Any, Optional, Union

ZERO: Any

class FixedOffset(tzinfo):
    def __init__(self, offset: Union[float, timedelta], name: str) -> None: ...
    def __getinitargs__(self): ...
    def utcoffset(self, dt: Optional[datetime]) -> timedelta: ...
    def tzname(self, dt: Optional[datetime]) -> str: ...
    def dst(self, dt: Optional[datetime]) -> timedelta: ...

utc: Any
