from typing import Any, Dict, Iterator, Optional, Union

from pymongo.client_session import ClientSession
from pymongo.collation import Collation
from pymongo.collection import Collection
from pymongo.pool import SocketInfo
from pymongo.write_concern import WriteConcern

class _Run:
    op_type: Any = ...
    index_map: Any = ...
    ops: Any = ...
    idx_offset: int = ...
    def __init__(self, op_type: int) -> None: ...
    def index(self, idx: int) -> int: ...
    def add(self, original_index: int, operation: Dict[str, Any]) -> None: ...

class _Bulk:
    collection: Any = ...
    ordered: Any = ...
    ops: Any = ...
    executed: bool = ...
    bypass_doc_val: Any = ...
    uses_collation: bool = ...
    uses_array_filters: bool = ...
    uses_hint: bool = ...
    is_retryable: bool = ...
    retrying: bool = ...
    started_retryable_write: bool = ...
    current_run: Any = ...
    def __init__(self, collection: Collection, ordered: bool, bypass_document_validation: bool) -> None: ...
    @property
    def bulk_ctx_class(self): ...
    def add_insert(self, document: Dict[str, Any]) -> None: ...
    def add_update(
        self,
        selector: Any,
        update: Any,
        multi: bool = ...,
        upsert: bool = ...,
        collation: Optional[Any] = ...,
        array_filters: Optional[Any] = ...,
        hint: Optional[Any] = ...,
    ) -> None: ...
    def add_replace(
        self, selector: Any, replacement: Any, upsert: bool = ..., collation: Optional[Any] = ..., hint: Optional[Any] = ...
    ) -> None: ...
    def add_delete(self, selector: Any, limit: Any, collation: Optional[Any] = ..., hint: Optional[Any] = ...) -> None: ...
    def gen_ordered(self) -> _Run: ...
    def gen_unordered(self) -> _Run: ...
    def execute_command(self, generator: SocketInfo, write_concern: Iterator[_Run], session: WriteConcern) -> Dict[str, Any]: ...
    def execute_insert_no_results(self, sock_info: Any, run: Any, op_id: Any, acknowledged: Any) -> None: ...
    def execute_op_msg_no_results(self, sock_info: Any, generator: Any) -> None: ...
    def execute_command_no_results(self, sock_info: Any, generator: Any) -> None: ...
    def execute_no_results(self, sock_info: SocketInfo, generator: Iterator[_Run]) -> None: ...
    def execute(self, write_concern: Any, session: Optional[ClientSession]): ...

class BulkUpsertOperation:
    def __init__(self, selector: Dict[str, Any], bulk: _Bulk, collation: Collation) -> None: ...
    def update_one(self, update: Dict[str, Any]) -> None: ...
    def update(self, update: Dict[str, Any]) -> None: ...
    def replace_one(self, replacement: Dict[str, Any]) -> None: ...

class BulkWriteOperation:
    def __init__(self, selector: Dict[str, Any], bulk: _Bulk, collation: Collation) -> None: ...
    def update_one(self, update: Dict[str, Any]) -> None: ...
    def update(self, update: Dict[str, Any]) -> None: ...
    def replace_one(self, replacement: Dict[str, Any]) -> None: ...
    def remove_one(self) -> None: ...
    def remove(self) -> None: ...
    def upsert(self) -> BulkUpsertOperation: ...

class BulkOperationBuilder:
    def __init__(self, collection: Collection, ordered: bool = ..., bypass_document_validation: bool = ...) -> None: ...
    def find(self, selector: Dict[str, Any], collation: Optional[Collation] = ...) -> BulkWriteOperation: ...
    def insert(self, document: Dict[str, Any]) -> None: ...
    def execute(self, write_concern: Optional[WriteConcern] = ...) -> Union[Dict[str, Any], None]: ...
