from typing import Any, Mapping, Optional

from pymongo.client_session import ClientSession

class ChangeStream:
    def __init__(
        self,
        target: Any,
        pipeline: Any,
        full_document: Any,
        resume_after: Any,
        max_await_time_ms: Any,
        batch_size: Any,
        collation: Any,
        start_at_operation_time: Any,
        session: Optional[ClientSession],
        start_after: Any,
    ) -> None: ...
    def close(self) -> None: ...
    def __iter__(self) -> Any: ...
    @property
    def resume_token(self): ...
    def next(self) -> Mapping[str, Any]: ...
    __next__: Any = ...
    @property
    def alive(self): ...
    def try_next(self): ...
    def __enter__(self): ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

class CollectionChangeStream(ChangeStream): ...
class DatabaseChangeStream(ChangeStream): ...
class ClusterChangeStream(DatabaseChangeStream): ...
