from typing import Any, Dict, Optional, Tuple

from pymongo.client_session import ClientSession
from pymongo.collection import Collection

class CommandCursor:
    def __init__(
        self,
        collection: Collection,
        cursor_info: Dict[str, Any],
        address: Tuple[str, int],
        retrieved: int = ...,
        batch_size: int = ...,
        max_await_time_ms: Optional[int] = ...,
        session: Optional[ClientSession] = ...,
        explicit_session: bool = ...,
    ) -> None: ...
    def __del__(self) -> None: ...
    def close(self) -> None: ...
    def batch_size(self, batch_size: int) -> CommandCursor: ...
    @property
    def alive(self) -> bool: ...
    @property
    def cursor_id(self) -> int: ...
    @property
    def address(self) -> Tuple[str, int]: ...
    @property
    def session(self): ...
    def __iter__(self) -> Any: ...
    def next(self) -> Dict[str, Any]: ...
    __next__: Any = ...
    def __enter__(self): ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

class RawBatchCommandCursor(CommandCursor):
    def __init__(
        self,
        collection: Any,
        cursor_info: Any,
        address: Any,
        retrieved: int = ...,
        batch_size: int = ...,
        max_await_time_ms: Optional[Any] = ...,
        session: Optional[ClientSession] = ...,
        explicit_session: bool = ...,
    ) -> None: ...
    def __getitem__(self, index: Any) -> None: ...
