from typing import Any, Iterable, List, Sequence, Union

def validate_compressors(dummy: Any, value: Union[str, Iterable[str]]) -> List[str]: ...
def validate_zlib_compression_level(option: str, value: Any) -> int: ...

class CompressionSettings:
    compressors: Any = ...
    zlib_compression_level: Any = ...
    def __init__(self, compressors: Sequence[str], zlib_compression_level: int) -> None: ...
    def get_compression_context(self, compressors: Sequence[str]) -> Union[SnappyContext, ZlibContext]: ...

class SnappyContext:
    compressor_id: int = ...
    @staticmethod
    def compress(data: bytes) -> bytes: ...

class ZlibContext:
    compressor_id: int = ...
    compress: Any = ...
    def __init__(self, level: int): ...

class ZstdContext:
    compressor_id: int = ...
    @staticmethod
    def compress(data: Any): ...

def decompress(data: bytes, compressor_id: int) -> bytes: ...
