from typing import Any, Dict, List, Mapping, Optional, Sequence, Union

from bson.codec_options import CodecOptions
from bson.dbref import DBRef
from pymongo import MongoClient, common
from pymongo.client_session import ClientSession
from pymongo.collection import Collection
from pymongo.read_concern import ReadConcern
from pymongo.read_preferences import _ServerMode
from pymongo.son_manipulator import SONManipulator
from pymongo.write_concern import WriteConcern

class Database(common.BaseObject):
    def __init__(
        self,
        client: MongoClient,
        name: str,
        codec_options: Optional[CodecOptions] = ...,
        read_preference: Optional[_ServerMode] = ...,
        write_concern: Optional[WriteConcern] = ...,
        read_concern: Optional[ReadConcern] = ...,
    ) -> None: ...
    def add_son_manipulator(self, manipulator: SONManipulator) -> None: ...
    @property
    def system_js(self) -> SystemJS: ...
    @property
    def client(self) -> MongoClient: ...
    @property
    def name(self) -> str: ...
    @property
    def incoming_manipulators(self) -> List[str]: ...
    @property
    def incoming_copying_manipulators(self) -> List[str]: ...
    @property
    def outgoing_manipulators(self) -> List[str]: ...
    @property
    def outgoing_copying_manipulators(self) -> List[str]: ...
    def with_options(
        self,
        codec_options: Optional[Any] = ...,
        read_preference: Optional[Any] = ...,
        write_concern: Optional[Any] = ...,
        read_concern: Optional[Any] = ...,
    ): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    def __getattr__(self, name: Any): ...
    def __getitem__(self, name: Any): ...
    def get_collection(
        self,
        name: str,
        codec_options: Optional[CodecOptions] = ...,
        read_preference: Optional[_ServerMode] = ...,
        write_concern: Optional[WriteConcern] = ...,
        read_concern: Optional[ReadConcern] = ...,
    ) -> Collection: ...
    def create_collection(
        self,
        name: str,
        codec_options: Optional[CodecOptions] = ...,
        read_preference: Optional[_ServerMode] = ...,
        write_concern: Optional[WriteConcern] = ...,
        read_concern: Optional[ReadConcern] = ...,
        session: Optional[ClientSession] = ...,
        **kwargs: Any,
    ) -> Collection: ...
    def aggregate(self, pipeline: Any, session: Optional[ClientSession] = ..., **kwargs: Any): ...
    def watch(
        self,
        pipeline: Optional[Any] = ...,
        full_document: Optional[Any] = ...,
        resume_after: Optional[Any] = ...,
        max_await_time_ms: Optional[Any] = ...,
        batch_size: Optional[Any] = ...,
        collation: Optional[Any] = ...,
        start_at_operation_time: Optional[Any] = ...,
        session: Optional[ClientSession] = ...,
        start_after: Optional[Any] = ...,
    ): ...
    def command(
        self,
        command: Union[str, Mapping[str, Any]],
        value: Optional[int] = ...,
        check: Optional[bool] = ...,
        allowable_errors: Optional[Sequence[str]] = ...,
        read_preference: Optional[_ServerMode] = ...,
        codec_options: Optional[CodecOptions] = ...,
        session: Optional[ClientSession] = ...,
        **kwargs: Any,
    ) -> Any: ...
    def list_collections(self, session: Optional[ClientSession] = ..., filter: Optional[Any] = ..., **kwargs: Any): ...
    def list_collection_names(self, session: Optional[ClientSession] = ..., filter: Optional[Any] = ..., **kwargs: Any): ...
    def collection_names(self, include_system_collections: bool = ..., session: Optional[ClientSession] = ...) -> List[str]: ...
    def drop_collection(
        self, name_or_collection: Union[str, Collection], session: Optional[ClientSession] = ...
    ) -> Dict[str, Any]: ...
    def validate_collection(
        self,
        name_or_collection: Any,
        scandata: bool = ...,
        full: bool = ...,
        session: Optional[ClientSession] = ...,
        background: Optional[Any] = ...,
    ): ...
    def current_op(self, include_all: bool = ..., session: Optional[ClientSession] = ...) -> Dict[str, Any]: ...
    def profiling_level(self, session: Optional[ClientSession] = ...) -> int: ...
    def set_profiling_level(self, level: int, slow_ms: Optional[int] = ..., session: Optional[ClientSession] = ...) -> None: ...
    def profiling_info(self, session: Optional[ClientSession] = ...) -> List[Any]: ...
    def error(self) -> Any: ...
    def last_status(self) -> Any: ...
    def previous_error(self) -> Any: ...
    def reset_error_history(self) -> None: ...
    def __iter__(self) -> Any: ...
    def __next__(self) -> None: ...
    next: Any = ...
    def add_user(
        self,
        name: str,
        password: Optional[str] = ...,
        read_only: Optional[bool] = ...,
        session: Optional[ClientSession] = ...,
        **kwargs: Any,
    ) -> None: ...
    def remove_user(self, name: str, session: Optional[ClientSession] = ...) -> None: ...
    def authenticate(
        self,
        name: Optional[str] = ...,
        password: Optional[str] = ...,
        source: Optional[str] = ...,
        mechanism: str = ...,
        **kwargs: Any,
    ) -> bool: ...
    def logout(self) -> None: ...
    def dereference(self, dbref: DBRef, session: Optional[ClientSession] = ..., **kwargs: Any) -> Dict[str, Any]: ...
    def eval(self, code: str, *args: Any) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> None: ...

class SystemJS:
    def __init__(self, database: Database) -> None: ...
    def __setattr__(self, name: Any, code: Any) -> None: ...
    def __setitem__(self, name: Any, code: Any) -> None: ...
    def __delattr__(self, name: Any) -> None: ...
    def __delitem__(self, name: Any) -> None: ...
    def __getattr__(self, name: Any): ...
    def __getitem__(self, name: Any): ...
    def list(self) -> List[str]: ...
