from typing import Any, Callable, Optional

class PeriodicExecutor:
    def __init__(self, interval: int, min_interval: int, target: Callable[..., Any], name: Optional[str] = ...) -> None: ...
    def open(self) -> None: ...
    def close(self, dummy: Optional[Any] = ...) -> None: ...
    def join(self, timeout: Optional[int] = ...) -> None: ...
    def wake(self) -> None: ...
    def update_interval(self, new_interval: Any) -> None: ...
    def skip_sleep(self) -> None: ...
