from typing import Any, Dict, Optional

class ReadConcern:
    def __init__(self, level: Optional[str] = ...) -> None: ...
    @property
    def level(self) -> Optional[str]: ...
    @property
    def ok_for_legacy(self) -> bool: ...
    @property
    def document(self) -> Dict[str, Any]: ...
    def __eq__(self, other: Any) -> bool: ...

DEFAULT_READ_CONCERN: ReadConcern
