import datetime
from typing import Any, Tuple

from pymongo.pool import Pool, SocketInfo

class Response:
    def __init__(self, data: Any, address: Any, request_id: Any, duration: Any, from_command: Any, docs: Any) -> None: ...
    @property
    def data(self) -> bytes: ...
    @property
    def address(self) -> Tuple[str, int]: ...
    @property
    def request_id(self) -> int: ...
    @property
    def duration(self) -> datetime.timedelta: ...
    @property
    def from_command(self) -> bool: ...
    @property
    def docs(self): ...

class ExhaustResponse(Response):
    def __init__(
        self, data: Any, address: Any, socket_info: Any, pool: Any, request_id: Any, duration: Any, from_command: Any, docs: Any
    ) -> None: ...
    @property
    def socket_info(self) -> SocketInfo: ...
    @property
    def pool(self) -> Pool: ...
